### PR TITLE
Add pd-lib-builder and Github CI for easy compilation for all Plataforms

### PR DESCRIPTION
**Pull request by charlesneimog**
Hi, 

I did some simple modifications to add pd-lib-builder, and it seems to compile for all platforms (I just tested it on Linux).

But as @porres mentioned #2, most objects work, but some objects and documentation have problems.  

For example, in `bamboo~` I have `zeroing delay lines`. I don't know what this means.

### CODE REVIEW

**Comment by porres** [comment]
legal, eu tb tava trabalhando nisso aqui https://github.com/porres/ooze

**Comment by porres** [comment]
So, yeah, I read the old conversation and I was really disappinted with this. I want to add STK instruments to ELSE, but it's also hard... see https://github.com/megrimm/pd-percolate/issues/2#issuecomment-313887952 

Idea was having 'ooze' as a place to start compiling these new objects

**Comment by porres** [comment]
I remember flext is a nightmare, maybe there's a way to do things differently

**Comment by porres** [comment]
seems ceammc uses some stk instruments, anyway, just saying this here cause we can add this stuff to ELSE if you want

**Comment by porres** [comment]
> For example, in bamboo~ I have zeroing delay lines. I don't know what this means.

In the source code this is ALWAYS printed no matter what, so it probably means someone was trying to debugg this to see what was going on and why there's no sound and didn't finish :)

**Comment by porres** [comment]
actually, a bang zeroes the delay lines and it just says so in the terminal (instead the help file) see tamb~, same thing, but no sound in both...

**Comment by charlesneimog** [comment]
Yeah, adding this to else would be great.

I will try to figure out what are the problems with these objects and look in ceammc. I wasn't aware of the stk thing rsrsrs.

I will start with bamboo~ because I like its name ahahah.

**Pull request merged**
